export enum ENV_KEYS {
    DATABASE_URL = "DATABASE_URL",
    PORT = "PORT",
    CLIENT_URL = "CLIENT_URL",
    JWT_ACCESS_SECRET = "JWT_ACCESS_SECRET",
    JWT_REFRESH_SECRET = "JWT_REFRESH_SECRET",
}
